name: Bad Pipeline  

on:
  push:
    branches:
      - main  # запуск при push в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # на последней версии Ubuntu
    steps:
      - uses: actions/checkout@v4  #
      - run: |
          cd lab3  # в директорию lab3
          mkdir build  # создаем директорию build
          cp main.py build/main.py  # копируем файл в директорию build

  test:
    runs-on: ubuntu-latest  # а последней версии Ubuntu
    steps:
      - uses: actions/checkout@v4  # код из репозитория
      - uses: actions/setup-python@v4  
        with:
          python-version: 3.12  # python версии 3.12
      - run: |
          cd lab3  # переходим в директорию lab3
          python -m pip install --upgrade pip  # pip до последней версии
          pip install pytest  # pytest для тестирования
      - run: |
          cd lab3  # в директорию lab3
          pytest test_main.py  # запуск тестов

